FROM php:8.2-cli
WORKDIR /var/www

RUN apt update && apt install -y unzip && \
    docker-php-ext-install pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

EXPOSE 8000
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
